package com.lhzkml.nowtest.core.designsystem.theme

import androidx.compose.ui.graphics.Color

/**
 * Jasmine colors.
 */
internal val primaryLight = Color(0xFF0B57D0)
internal val onPrimaryLight = Color(0xFFFFFFFF)
internal val primaryContainerLight = Color(0xFFD3E3FD)
internal val onPrimaryContainerLight = Color(0xFF0842A0)
internal val secondaryLight = Color(0xFF00639B)
internal val onSecondaryLight = Color(0xFFFFFFFF)
internal val secondaryContainerLight = Color(0xFFC2E7FF)
internal val onSecondaryContainerLight = Color(0xFF004A77)
internal val tertiaryLight = Color(0xFF146C2E)
internal val onTertiaryLight = Color(0xFFFFFFFF)
internal val tertiaryContainerLight = Color(0xFFC4EED0)
internal val onTertiaryContainerLight = Color(0xFF0F5223)
internal val errorLight = Color(0xFFB3261E)
internal val onErrorLight = Color(0xFFFFFFFF)
internal val errorContainerLight = Color(0xFFF9DEDC)
internal val onErrorContainerLight = Color(0xFF8C1D18)
internal val backgroundLight = Color(0xFFFFFFFF)
internal val onBackgroundLight = Color(0xFF1F1F1F)
internal val surfaceLight = Color(0xFFFFFFFF)
internal val onSurfaceLight = Color(0xFF1F1F1F)
internal val surfaceVariantLight = Color(0xFFE1E3E1)
internal val onSurfaceVariantLight = Color(0xFF444746)
internal val surfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val surfaceContainerLowLight = Color(0xFFF8FAFD)
internal val surfaceContainerLight = Color(0xFFF0F4F9)
internal val surfaceContainerHighLight = Color(0xFFE9EEF6)
internal val surfaceContainerHighestLight = Color(0xFFDDE3EA)
internal val inverseSurfaceLight = Color(0xFF303030)
internal val inverseOnSurfaceLight = Color(0xFFF2F2F2)
internal val outlineLight = Color(0xFF747775)
internal val outlineVariantLight = Color(0xFFC4C7C5)
internal val inversePrimaryLight = Color(0xFFA8C7FA)
internal val surfaceDimLight = Color(0xFFD3DBE5)
internal val surfaceBrightLight = Color(0xFFFFFFFF)
internal val scrimLight = Color(0xFF000000)

internal val primaryDark = Color(0xFFA8C7FA)
internal val onPrimaryDark = Color(0xFF062E6F)
internal val primaryContainerDark = Color(0xFF0842A0)
internal val onPrimaryContainerDark = Color(0xFFD3E3FD)
internal val secondaryDark = Color(0xFF7FCFFF)
internal val onSecondaryDark = Color(0xFF003355)
internal val secondaryContainerDark = Color(0xFF004A77)
internal val onSecondaryContainerDark = Color(0xFFC2E7FF)
internal val tertiaryDark = Color(0xFF6DD58C)
internal val onTertiaryDark = Color(0xFF0A3818)
internal val tertiaryContainerDark = Color(0xFF0F5223)
internal val onTertiaryContainerDark = Color(0xFFC4EED0)
internal val errorDark = Color(0xFFF2B8B5)
internal val onErrorDark = Color(0xFF601410)
internal val errorContainerDark = Color(0xFF8C1D18)
internal val onErrorContainerDark = Color(0xFFF9DEDC)
internal val backgroundDark = Color(0xFF131314)
internal val onBackgroundDark = Color(0xFFE3E3E3)
internal val surfaceDark = Color(0xFF131314)
internal val onSurfaceDark = Color(0xFFE3E3E3)
internal val surfaceVariantDark = Color(0xFF444746)
internal val onSurfaceVariantDark = Color(0xFFC4C7C5)
internal val surfaceContainerLowestDark = Color(0xFF0E0E0E)
internal val surfaceContainerLowDark = Color(0xFF1B1B1B)
internal val surfaceContainerDark = Color(0xFF1E1F20)
internal val surfaceContainerHighDark = Color(0xFF282A2C)
internal val surfaceContainerHighestDark = Color(0xFF333537)
internal val inverseSurfaceDark = Color(0xFFE3E3E3)
internal val inverseOnSurfaceDark = Color(0xFF303030)
internal val outlineDark = Color(0xFF8E918F)
internal val outlineVariantDark = Color(0xFF444746)
internal val inversePrimaryDark = Color(0xFF0B57D0)
internal val surfaceDimDark = Color(0xFF131314)
internal val surfaceBrightDark = Color(0xFF37393B)
internal val scrimDark = Color(0xFF000000)
